[program:php-fpm]
command=php-fpm
user=root
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.stdout
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:sshd]
command=/usr/sbin/sshd -D
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.stdout
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:messenger-consume]
command=php /var/www/symfony/bin/console messenger:consume async --time-limit=3600 --memory-limit=128M
directory=/var/www/symfony
user=www-data
autostart=%(ENV_ASYNC_AUTOSTART)s
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:messenger-scheduler]
command=php /var/www/symfony/bin/console messenger:consume scheduler_default --time-limit=3600 --memory-limit=128M
directory=/var/www/symfony
user=www-data
autostart=%(ENV_SCHEDULER_AUTOSTART)s
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
