# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    default_locale: '%env(APP_LOCALE)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    http_client:
        scoped_clients:
            lspskp.client:
                base_uri: '%env(LSPSKP_API_BASE_URL)%'
                verify_peer: false
                headers:
                    Authorization: 'Bearer %env(LSPSKP_API_TOKEN)%'

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
