# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    email:
        enabled: true
        mailer: App\Service\Admin\SchebAuthCodeMailer
        sender_email: '%app.mailer_from%'
        sender_name: '%app.short_name%'
        digits: 6
        template: admin/2fa_form.html.twig
