vich_uploader:
    db_driver: orm
    storage: flysystem
    mappings:
        files:
            uri_prefix: /files
            upload_destination: s3.storage
            namer: App\Naming\SluggedSmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
