services:
    db:
        volumes:
            - ./docker/.data/db:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: sf
            POSTGRES_USER: sf
            POSTGRES_DB: sf
        networks:
            default:
                ipv4_address: 172.34.21.20

    app:
        build:
            args:
                COPY_SOURCE: "./.gitignore"
                INSTALL_PACKAGES: 0
                ENABLE_PHP_PRELOAD: 0
        volumes:
            - ./:/var/www/symfony
        ports:
            - "8080:80"

    localstack:
        environment:
            - SERVICES=s3
            - DEBUG=1
            - DATA_DIR=/localstack/data
        volumes:
            - ./docker/.data/localstack:/localstack
            - /var/run/docker.sock:/var/run/docker.sock
            - ./docker/localstack/s3:/docker-entrypoint-initaws.d
        networks:
            default:
                ipv4_address: 172.34.21.30

networks:
    default:
        name: base-sf-project
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: 172.34.21.0/24
