services:
    db:
        image: postgres:17
    db-test:
        image: postgres:17
    app:
        build:
            dockerfile: docker/app/Dockerfile
    localstack:
        image: localstack/localstack:0.11.0
